### ISSUE TITLE
Concurrent Rendering Intro video doesn't seem correct and displays Intro to Client Components  instead?

### ISSUE THREAD

**Issue by wingy3181** [epicweb-dev/react-performance#129]
Hi @kentcdodds 

Seems like the intro video for concurrent rendering is wrong? 
It is showing me the Client Components intro instead

See screenshots below of the hosted version (but the same happens on local):

https://www.epicreact.dev/workshops/react-performance/concurrent-rendering-intro
<img width="1368" alt="image" src="https://github.com/user-attachments/assets/393fbfae-3634-4245-ae18-408aac9413e5">

https://www.epicreact.dev/workshops/react-server-components/intro-to-client-components
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/98b8a808-920e-4f0d-9b99-5f856c7407f1">

Or let me know if it is something on my end

**Comment by kentcdodds** [comment]
Thank you. I've let the team know.
